### ISSUE TITLE
Complex phsp factor produces nonsensical intensity

### ISSUE THREAD

**Issue by sebastianJaeger** [ComPWA/ampform#235]
If the complex phasespace factor is used to model a resonance below the kinematic threshold, the resulting intensity has an extremely high and sharp peak at a (seemingly) random position within the kinematic borders. A minimal working example to generate a model with this problem is:

```python
import qrules
from ampform.dynamics import PhaseSpaceFactorComplex
from ampform.dynamics.builder import RelativisticBreitWignerBuilder
from ampform import get_builder

reaction = qrules.generate_transitions(
    initial_state=("J/psi(1S)", [-1, +1]),
    final_state=["p", "p~", "eta"],
    allowed_intermediate_particles=[
        "N(1440)",                            
    ],
    allowed_interaction_types=["strong", "EM"],
    formalism="canonical-helicity",
    mass_conservation_factor=1,
)

model_builder = get_builder(reaction)

complex_bw_builder = RelativisticBreitWignerBuilder(form_factor=True, phsp_factor=PhaseSpaceFactorComplex)
for name in reaction.get_intermediate_particles().names:
    model_builder.set_dynamics(name, complex_bw_builder)
        
model = model_builder.formulate()
```

 Attached is a simple plot of the distribution of events generated with this model.
[Complex_PHSP_Factor_example.pdf](https://github.com/ComPWA/ampform/files/8069306/Complex_PHSP_Factor_example.pdf)

**Comment by redeboer** [comment]
Hi @sebastianJaeger, thanks for your report. I adapted your code snippet a bit so that it has exactly one resonance and extended it so that it generates momenta. (Note: it's not necessary to generate a hit-and-miss _data_ sample to view the intensity distribution.)

<details>
<summary>Extended code snippet</summary>

Running on ComPWA/ampform@cfca442 and ComPWA/tensorwaves@e422bce:

```python
import ampform
import matplotlib.pyplot as plt
import numpy as np
import qrules
from ampform.dynamics import PhaseSpaceFactorComplex
from ampform.dynamics.builder import RelativisticBreitWignerBuilder
from matplotlib import cm
from tensorwaves.data import (
    SympyDataTransformer,
    TFPhaseSpaceGenerator,
    TFUniformRealNumberGenerator,
)
from tensorwaves.function.sympy import create_parametrized_function

# Generate model
reaction = qrules.generate_transitions(
    initial_state=("J/psi(1S)", [-1, +1]),
    final_state=["p", "p~", "eta"],
    allowed_intermediate_particles=[
        "N(1440)+",
    ],
    allowed_interaction_types=["strong", "EM"],
    formalism="canonical-helicity",
    mass_conservation_factor=1,
)

model_builder = ampform.get_builder(reaction)
breit_wigner_builder = RelativisticBreitWignerBuilder(
    form_factor=True, phsp_factor=PhaseSpaceFactorComplex
)
for name in reaction.get_intermediate_particles().names:
    model_builder.set_dynamics(name, breit_wigner_builder)
model = model_builder.formulate()

# Generate phase space sample
rng = TFUniformRealNumberGenerator(seed=0)
phsp_generator = TFPhaseSpaceGenerator(
    initial_state_mass=reaction.initial_state[-1].mass,
    final_state_masses={
        i: p.mass for i, p in reaction.final_state.items()
    },
)
phsp_momenta = phsp_generator.generate(1_000_000, rng)
helicity_transformer = SympyDataTransformer.from_sympy(
    model.kinematic_variables, backend="jax"
)
phsp = helicity_transformer(phsp_momenta)

# Visualize intensity distribution
unfolded_expression = model.expression.doit()
intensity_func = create_parametrized_function(
    expression=unfolded_expression,
    parameters=model.parameter_defaults,
    backend="jax",
)

fig, ax = plt.subplots(figsize=(9, 4))
intensities = intensity_func(phsp)
ax.hist(
    np.array(phsp["m_02"].real),
    weights=np.array(intensities),
    bins=200,
    alpha=0.5,
    density=True,
)
ax.set_yscale("log")
ax.set_xlabel(R"$m_{p\eta}$ [GeV]")

resonances = sorted(
    reaction.get_intermediate_particles(),
    key=lambda p: p.mass,
)
evenly_spaced_interval = np.linspace(0, 1, len(resonances))
colors = [cm.rainbow(x) for x in evenly_spaced_interval]
for p, color in zip(resonances, colors):
    ax.axvline(x=p.mass, linestyle="dotted", label=p.name, color=color)
ax.legend()
plt.show()
```

</details>

![image](https://user-images.githubusercontent.com/29308176/154091258-c81d9980-1c88-4054-96bf-707c1cedfe9e.png)

Initially, I thought that something was wrong with the new Breit-Wigner builder (#206), but if the same script is run on a resonance above threshold (where [`PhaseSpaceFactorComplex`](https://ampform.readthedocs.io/en/0.12.x/api/ampform.dynamics.html#ampform.dynamics.PhaseSpaceFactorComplex) is equivalent to the default [`PhaseSpaceFactor`](https://ampform.readthedocs.io/en/0.12.x/api/ampform.dynamics.html#ampform.dynamics.PhaseSpaceFactor)), the distribution look smooth.

<details>
<summary>Snippet to generate resonance above threshold</summary>

```python
reaction = qrules.generate_transitions(
    initial_state=("J/psi(1S)", [-1, +1]),
    final_state=["gamma", "pi0", "pi0"],
    allowed_intermediate_particles=["f(0)(980)"],
    allowed_interaction_types=["strong", "EM"],
)
```

</details>

My guess is that this phase space factor simply does not make sense for decay products with unequal masses (here: N* -> proton eta), see #151. `PhaseSpaceFactorComplex` only makes sure that numbers are produced for the negative values under its square root, but the physics probably does not make sense. An idea may be to to investigate the model interactively as shown in [this tutorial](https://ampform.readthedocs.io/en/0.12.x/usage/interactive.html).

**Comment by redeboer** [comment]
Another observation: the peak seems to originate from the form factor. Same code as in https://github.com/ComPWA/ampform/issues/235#issuecomment-1040415722 with `RelativisticBreitWignerBuilder(form_factor=False, ...)` results in:

<details>

Versions: ComPWA/ampform@cfca442 and ComPWA/tensorwaves@e422bce

```python
%config InlineBackend.figure_formats = ['svg']
import ampform
import matplotlib.pyplot as plt
import numpy as np
import qrules
from ampform.dynamics import PhaseSpaceFactorComplex
from ampform.dynamics.builder import RelativisticBreitWignerBuilder
from matplotlib import cm
from tensorwaves.data import (
    SympyDataTransformer,
    TFPhaseSpaceGenerator,
    TFUniformRealNumberGenerator,
)
from tensorwaves.function.sympy import create_parametrized_function

# Generate model
reaction = qrules.generate_transitions(
    initial_state=("J/psi(1S)", [-1, +1]),
    final_state=["p", "p~", "eta"],
    allowed_intermediate_particles=["N(1440)+"],
    allowed_interaction_types=["strong", "EM"],
    mass_conservation_factor=1,
)

model_builder = ampform.get_builder(reaction)
breit_wigner_builder = RelativisticBreitWignerBuilder(
    form_factor=False,
    phsp_factor=PhaseSpaceFactorComplex,
)
for name in reaction.get_intermediate_particles().names:
    model_builder.set_dynamics(name, breit_wigner_builder)
model = model_builder.formulate()

# Generate phase space sample
rng = TFUniformRealNumberGenerator(seed=0)
phsp_generator = TFPhaseSpaceGenerator(
    initial_state_mass=reaction.initial_state[-1].mass,
    final_state_masses={i: p.mass for i, p in reaction.final_state.items()},
)
phsp_momenta = phsp_generator.generate(1_000_000, rng)
helicity_transformer = SympyDataTransformer.from_sympy(
    model.kinematic_variables, backend="jax"
)
phsp = helicity_transformer(phsp_momenta)

# Visualize intensity distribution
unfolded_expression = model.expression.doit()
intensity_func = create_parametrized_function(
    expression=unfolded_expression,
    parameters=model.parameter_defaults,
    backend="jax",
)

fig, ax = plt.subplots(figsize=(9, 4))
intensities = intensity_func(phsp)
ax.hist(
    np.array(phsp["m_02"].real),
    weights=np.array(intensities),
    bins=200,
    alpha=0.5,
    density=True,
)
ax.set_yscale("log")
ax.set_xlabel(R"$m_{p\eta}$ [GeV]")

resonances = sorted(
    reaction.get_intermediate_particles(),
    key=lambda p: p.mass,
)
evenly_spaced_interval = np.linspace(0, 1, len(resonances))
colors = [cm.rainbow(x) for x in evenly_spaced_interval]
for p, color in zip(resonances, colors):
    ax.axvline(x=p.mass, linestyle="dotted", label=p.name, color=color)
ax.legend()
plt.show()
```

</details>

![image](https://user-images.githubusercontent.com/29308176/154098111-5a815777-3b87-4ab5-ae77-f6b6cb395b7b.png)

This seems to be a bug, though, because setting `form_factor=False` also switches off the energy dependent width (where the phase space factor is of relevance), letting it fall back to a standard [`relativistic_breit_wigner()`](https://ampform.readthedocs.io/en/0.12.x/api/ampform.dynamics.html#ampform.dynamics.relativistic_breit_wigner).


<details>

```python
model.expression.args[0].args[0].args[0].args[0].doit()
```

</details>

![image](https://user-images.githubusercontent.com/29308176/154098899-433b4964-41af-4769-a6dd-168c5949e3d6.png)

**Comment by redeboer** [comment]
> Another observation: the peak seems to originate from the form factor.

Okay, I take that back.
#236 makes it possible to independently add a form factor and/or set an energy-dependent width. Playing around a bit with that and also making the final state masses equal (proton gets eta mass) gives me the impression that
1. the peak comes from the energy dependent width.
2. the peak becomes more extreme the closer the sub-threshold resonance is to threshold.
3. with `PhaseSpaceFactorComplex`, it doesn't matter whether the masses of the decay product are equal or not.


<details>

**Note**: this code could be simplified with [scalar masses](https://ampform.readthedocs.io/en/0.12.x/usage/amplitude.html#scalar-masses), which turns the final state masses into parameters.

```shell
pip install \
  git+https://github.com/ComPWA/ampform@3ed3ed5 \
  "tensorwaves[jax,pwa] @ git+https://github.com/ComPWA/tensorwaves@bea8cd9"
```

```python
# %config InlineBackend.figure_formats = ['svg']
import ampform
import attrs
import matplotlib.pyplot as plt
import numpy as np
import qrules
from ampform.dynamics import PhaseSpaceFactorComplex
from ampform.dynamics.builder import RelativisticBreitWignerBuilder
from matplotlib import cm

from tensorwaves.data import (
    SympyDataTransformer,
    TFPhaseSpaceGenerator,
    TFUniformRealNumberGenerator,
)
from tensorwaves.function.sympy import create_parametrized_function

# Modify particle masses
PDG = qrules.load_pdg()
eta_mass = PDG["eta"].mass
proton_mass = PDG["eta"].mass
resonance_mass = 0.9 * (proton_mass + eta_mass)

particle_set = set(PDG)

particle = PDG["p"]
modified_particle = attrs.evolve(particle, mass=proton_mass)
particle_set.remove(particle)
particle_set.add(modified_particle)

particle = PDG["N(1440)+"]
modified_particle = attrs.evolve(particle, mass=resonance_mass)
particle_set.remove(particle)
particle_set.add(modified_particle)

PDG = qrules.ParticleCollection(particle_set)

# Create amplitude model
reaction = qrules.generate_transitions(
    initial_state=("J/psi(1S)", [+1]),
    final_state=["p", "p~", "eta"],
    allowed_intermediate_particles=["N(1440)+"],
    allowed_interaction_types=["strong", "EM"],
    particle_db=PDG,
    mass_conservation_factor=1,
    # max_angular_momentum=1,  # filter out L=2
)
assert len(reaction.get_intermediate_particles()) == 1

model_builder = ampform.get_builder(reaction)
breit_wigner_builder = RelativisticBreitWignerBuilder(
    phsp_factor=PhaseSpaceFactorComplex
)
for name in reaction.get_intermediate_particles().names:
    model_builder.set_dynamics(name, breit_wigner_builder)

breit_wigner_builder.energy_dependent_width = False
breit_wigner_builder.form_factor = False
model_standard_bw = model_builder.formulate()

breit_wigner_builder.energy_dependent_width = False
breit_wigner_builder.form_factor = True
model_standard_bw_with_ff = model_builder.formulate()

breit_wigner_builder.energy_dependent_width = True
breit_wigner_builder.form_factor = False
model_energy_dependent = model_builder.formulate()

breit_wigner_builder.energy_dependent_width = True
breit_wigner_builder.form_factor = True
model_energy_dependent_with_ff = model_builder.formulate()

# Generate phase space sample
rng = TFUniformRealNumberGenerator(seed=0)
phsp_generator = TFPhaseSpaceGenerator(
    initial_state_mass=reaction.initial_state[-1].mass,
    final_state_masses={i: p.mass for i, p in reaction.final_state.items()},
)
phsp_momenta = phsp_generator.generate(1_000_000, rng)
helicity_transformer = SympyDataTransformer.from_sympy(
    model_standard_bw.kinematic_variables, backend="jax"
)
phsp = helicity_transformer(phsp_momenta)
phsp = {k: v.real for k, v in phsp.items()}  # important for sqrt of Blatt-Weisskopf!

# Generate intensity distributions
func_standard_bw = create_parametrized_function(
    expression=model_standard_bw.expression.doit(),
    parameters=model_standard_bw.parameter_defaults,
    backend="jax",
)
func_standard_bw_with_ff = create_parametrized_function(
    expression=model_standard_bw_with_ff.expression.doit(),
    parameters=model_standard_bw_with_ff.parameter_defaults,
    backend="jax",
)
func_energy_dependent = create_parametrized_function(
    expression=model_energy_dependent.expression.doit(),
    parameters=model_energy_dependent.parameter_defaults,
    backend="jax",
)
func_energy_dependent_with_ff = create_parametrized_function(
    expression=model_energy_dependent_with_ff.expression.doit(),
    parameters=model_energy_dependent_with_ff.parameter_defaults,
    backend="jax",
)

# Plot 'em!
fig, ax = plt.subplots(figsize=(9, 4))

hist_kwargs = dict(
    bins=200,
    histtype="step",
    density=True,
)
ax.hist(
    np.array(phsp["m_02"].real),
    weights=np.array(func_standard_bw(phsp)),
    label="Standard Breit-Wigner",
    **hist_kwargs,
)
ax.hist(
    np.array(phsp["m_02"].real),
    weights=np.array(func_standard_bw_with_ff(phsp)),
    label="Standard Breit-Wigner with form factor",
    linestyle="dotted",
    **hist_kwargs,
)
ax.hist(
    np.array(phsp["m_02"].real),
    weights=np.array(func_energy_dependent(phsp)),
    label="Energy-dependent Breit-Wigner",
    **hist_kwargs,
)
ax.hist(
    np.array(phsp["m_02"].real),
    weights=np.array(func_energy_dependent_with_ff(phsp)),
    label="Energy-dependent Breit-Wigner with form factor",
    linestyle="dotted",
    **hist_kwargs,
)

ax.set_yscale("log")
ax.set_xlabel(R"$m_{p\eta}$ [GeV]")

resonances = sorted(
    reaction.get_intermediate_particles(),
    key=lambda p: p.mass,
)
evenly_spaced_interval = np.linspace(0, 1, len(resonances))
colors = [cm.rainbow(x) for x in evenly_spaced_interval]
for p, color in zip(resonances, colors):
    ax.axvline(x=p.mass, linestyle="dotted", label=p.name, color=color)
ax.legend()
plt.show()
```

</details>

### N(1440)⁺ mass at 97% of proton+eta mass
![image](https://user-images.githubusercontent.com/29308176/154259517-400963b9-e775-45f5-b1d4-22d65e439130.png)

### N(1440)⁺ mass at 99% of proton+eta mass
![image](https://user-images.githubusercontent.com/29308176/154260065-2e666f45-e139-4f71-8da2-3e1f8e412028.png)

### N(1440)⁺ mass at 95% of 2x eta mass (proton mass set to eta mass)
![image](https://user-images.githubusercontent.com/29308176/154259754-47c78b90-0610-4c94-9236-6247f5967ccc.png)

**Comment by redeboer** [comment]
@sebastianJaeger, it may be worth looking into the new Resonances section of the PDG. Existing implementation is based on PDG 2020. For the energy dependent width, compare in particular:
- [PDG, §Resonances, Eq. (49.21)](https://pdg.lbl.gov/2020/reviews/rpp2020-rev-resonances.pdf#page=6)
- [PDG, §Resonances, Eq. (50.25)](https://pdg.lbl.gov/2021/reviews/rpp2021-rev-resonances.pdf#page=9)

**Comment by redeboer** [comment]
This problem is probably fixed through #265: the narrow peak is probably an artifact of the phase space factor behaviour below _m₁-m₂_. [Figure below](https://ampform.readthedocs.io/en/latest/usage/dynamics/analytic-continuation.html) shows the phase space factors that were implemented as of posting this bug report. Chew-Mandelstam (lower right) displays the proper behaviour below _m₁-m₂_.
![image](https://user-images.githubusercontent.com/29308176/162178128-cdd54d65-2a16-47ee-9053-ba68371ace91.png)

**Comment by redeboer** [comment]
`PhaseSpaceFactorSWave` https://github.com/ComPWA/ampform/issues/235#issuecomment-1091517618 should display the  correct behaviour. There is still a narrow peak, but this is expected behaviour (after some discussion with @mmikhasenko).

<details>
<summary>
Sub-threshold Breit-Wigner comparison form <a href="https://ampform.readthedocs.io/en/latest/usage/dynamics.html#analytic-continuation">this page</a>, <i>without phase space</i>.</summary>

![image](https://user-images.githubusercontent.com/29308176/162261655-3ed4b2f1-6d03-45e5-a92a-21542af5eea3.png)

</details>

Note that, technically speaking, one should compute the phase space factor from the dispersion integral ([TR-003](https://compwa-org.readthedocs.io/report/003.html#general-dispersion-integral)) in the case of higher angular momenta (here: L=1), but using this phase space factor for _S_-waves at least ensures better behaviour of the phase space factor below threshold.

---

_Modified snippet of https://github.com/ComPWA/ampform/issues/235#issuecomment-1041414226_

### N(1440)⁺ mass set to 97% of p+η mass
<details>
<summary>Source code</summary>

```shell
pip install ampform==0.14.0 tensorwaves[jax,pwa]==0.4.3
```

```python
# %config InlineBackend.figure_formats = ['svg']
import ampform
import attrs
import matplotlib.pyplot as plt
import numpy as np
import qrules
from ampform.dynamics import PhaseSpaceFactorSWave
from ampform.dynamics.builder import RelativisticBreitWignerBuilder
from matplotlib import cm

from tensorwaves.data import (
    SympyDataTransformer,
    TFPhaseSpaceGenerator,
    TFUniformRealNumberGenerator,
)
from tensorwaves.function.sympy import create_parametrized_function

# Modify particle masses
PDG = qrules.load_pdg()
eta_mass = PDG["eta"].mass
proton_mass = PDG["eta"].mass
resonance_mass = 0.97 * (proton_mass + eta_mass)

particle_set = set(PDG)

particle = PDG["p"]
modified_particle = attrs.evolve(particle, mass=proton_mass)
particle_set.remove(particle)
particle_set.add(modified_particle)

particle = PDG["N(1440)+"]
modified_particle = attrs.evolve(particle, mass=resonance_mass)
particle_set.remove(particle)
particle_set.add(modified_particle)

PDG = qrules.ParticleCollection(particle_set)

# Create amplitude model
reaction = qrules.generate_transitions(
    initial_state=("J/psi(1S)", [+1]),
    final_state=["p", "p~", "eta"],
    allowed_intermediate_particles=["N(1440)+"],
    allowed_interaction_types=["strong", "EM"],
    particle_db=PDG,
    mass_conservation_factor=1,
)
assert len(reaction.get_intermediate_particles()) == 1

model_builder = ampform.get_builder(reaction)
model_builder.scalar_initial_state_mass = True
model_builder.stable_final_state_ids = [0, 1, 2]
breit_wigner_builder = RelativisticBreitWignerBuilder(
    phsp_factor=PhaseSpaceFactorSWave   # <-- fixes the problem
)
for name in reaction.get_intermediate_particles().names:
    model_builder.set_dynamics(name, breit_wigner_builder)

breit_wigner_builder.energy_dependent_width = False
breit_wigner_builder.form_factor = False
model_standard_bw = model_builder.formulate()

breit_wigner_builder.energy_dependent_width = False
breit_wigner_builder.form_factor = True
model_standard_bw_with_ff = model_builder.formulate()

breit_wigner_builder.energy_dependent_width = True
breit_wigner_builder.form_factor = False
model_energy_dependent = model_builder.formulate()

breit_wigner_builder.energy_dependent_width = True
breit_wigner_builder.form_factor = True
model_energy_dependent_with_ff = model_builder.formulate()

# Generate phase space sample
rng = TFUniformRealNumberGenerator(seed=0)
phsp_generator = TFPhaseSpaceGenerator(
    initial_state_mass=reaction.initial_state[-1].mass,
    final_state_masses={i: p.mass for i, p in reaction.final_state.items()},
)
phsp_momenta = phsp_generator.generate(1_000_000, rng)
helicity_transformer = SympyDataTransformer.from_sympy(
    model_standard_bw.kinematic_variables, backend="jax"
)
phsp = helicity_transformer(phsp_momenta)
phsp = {k: v.real for k, v in phsp.items()}  # important for sqrt of Blatt-Weisskopf!

# Generate intensity distributions
func_standard_bw = create_parametrized_function(
    expression=model_standard_bw.expression.doit(),
    parameters=model_standard_bw.parameter_defaults,
    backend="jax",
)
func_standard_bw_with_ff = create_parametrized_function(
    expression=model_standard_bw_with_ff.expression.doit(),
    parameters=model_standard_bw_with_ff.parameter_defaults,
    backend="jax",
)
func_energy_dependent = create_parametrized_function(
    expression=model_energy_dependent.expression.doit(),
    parameters=model_energy_dependent.parameter_defaults,
    backend="jax",
)
func_energy_dependent_with_ff = create_parametrized_function(
    expression=model_energy_dependent_with_ff.expression.doit(),
    parameters=model_energy_dependent_with_ff.parameter_defaults,
    backend="jax",
)

# Plot 'em!
fig, ax = plt.subplots(figsize=(9, 4))

hist_kwargs = dict(
    bins=200,
    histtype="step",
    density=True,
)
ax.hist(
    np.array(phsp["m_02"].real),
    weights=np.array(func_standard_bw(phsp)),
    label="Standard Breit-Wigner",
    **hist_kwargs,
)
ax.hist(
    np.array(phsp["m_02"].real),
    weights=np.array(func_standard_bw_with_ff(phsp)),
    label="Standard Breit-Wigner with form factor",
    linestyle="dotted",
    **hist_kwargs,
)
ax.hist(
    np.array(phsp["m_02"].real),
    weights=np.array(func_energy_dependent(phsp)),
    label="Energy-dependent Breit-Wigner",
    **hist_kwargs,
)
ax.hist(
    np.array(phsp["m_02"].real),
    weights=np.array(func_energy_dependent_with_ff(phsp)),
    label="Energy-dependent Breit-Wigner with form factor",
    linestyle="dotted",
    **hist_kwargs,
)

ax.set_yscale("log")
ax.set_xlabel(R"$m_{p\eta}$ [GeV]")

resonances = sorted(
    reaction.get_intermediate_particles(),
    key=lambda p: p.mass,
)
evenly_spaced_interval = np.linspace(0, 1, len(resonances))
colors = [cm.rainbow(x) for x in evenly_spaced_interval]
for p, color in zip(resonances, colors):
    ax.axvline(x=p.mass, linestyle="dotted", label=p.name, color=color)
ax.legend()
plt.show()
```

</details>

![image](https://user-images.githubusercontent.com/29308176/162259310-f721c5d1-6303-413e-b746-21f3a15e583f.png)

**Comment by redeboer** [comment]
- [ ] Normal Breit-Wigner @sebastianJaeger 
- [ ] `PhaseSpaceFactorSWave` @sebastianJaeger 
- [ ] Dispersion integral -> @redeboer

**Comment by mmikhasenko** [comment]
Let me add to the discussion.
 - Once you want to describe the state with the mass below the threshold you have to be careful. The standard single channel Breit-Wigner won't be correct approach.
 - The most common case (including N1440) is when you describe a state predominately decaying to the channel A with the lower threshold (N->ppi), while you want to describe the channel B with the higher threshold (N->p eta). In that case, you should
   - Call the standard Breit-Wigner with the masses of `p` and `pi`.
   - Plot against `m(ppi)` make sure it looks right, the mass and width
   - multiple this `|BW|^2` by the phase space of the channel B.

**Comment by redeboer** [comment]
Thanks for your feedback!

> Once you want to describe the state with the mass below the threshold you have to be careful. The standard single channel Breit-Wigner won't be correct approach.

The analysis will for now remain an efficiency study, so it was decided that a normal BW suffices for now just to describe the distribution (without the resonance positions necessarily making sense).

> The most common case (including N1440) is when you describe a state predominately decaying to the channel A with the lower threshold (N->ppi), while you want to describe the channel B with the higher threshold (N->p eta).

Yes, you mentioned. From an internal note:
_N(1440) [predominantly decays to pπ](https://pdglive.lbl.gov/Particle.action?init=0&node=B061&home=BXXX005), not pη. This has effect on the energy-dependent width (see e.g. https://github.com/ComPWA/ampform/issues/235), through [PDG2021 Equation (50.24-25)](https://pdg.lbl.gov/2021/reviews/rpp2021-rev-resonances.pdf#page=9): the coupling g for pπ dominates in this sum over the g for pη._
The way I understand it, is that you can use a pion mass instead of an eta mass in Eq. (50.28), because the coupling for pη in Eq. (50.25) is much smaller than that for pπ. This removes the need for a phase space factor with analytic continuation.

Your recommendations can be addressed once the analysis can move to an actual PWA stage.

**Comment by mmikhasenko** [comment]
Just one more practical thing:
 - once you add p eta channel with whatever fraction, the first thing to look at is m(ppi) again and check the mass and the width, renormalize them. It is needed because the higher threshold will impact the peak position, as you well see.
